wip: working example for multithreading
NEARBuilders/near-api-lib-rs pull request #58
Opened 2024-05-17 07:49 UTC by jaswinder6991

2024-05-17 07:54 UTC, jaswinder6991 commented
Fixes #47

2024-05-18 07:50 UTC, ckshitij approved these changes

2024-05-18 08:24 UTC, ckshitij requested changes
Please check and update all the **Arc< dyn Provider >** with **( Arc< dyn Provider + Send + Sync>)** below are function names: 

- view_function 
- view_state
- get_access_key
- state

2024-05-18 08:32 UTC, ckshitij commented on near-accounts/src/accounts.rs
> +    provider: Arc<dyn Provider + Send + Sync>,
[Suggestion]:  you can define Alias for the same as well, ```type ProviderArc = Arc<dyn Provider + Send + Sync>;```

2024-05-21 16:03 UTC, ckshitij approved these changes
One minor comment, apart from this changes looks good to me.

2024-05-23 07:25 UTC, merged